name: MacOS Build


on: [push]

jobs:
  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install glib
      run: brew install glib
    - name: Install gtk3
      run: brew install gtk+3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build cli
      working-directory: ./ll-cli
      run: cargo build --release --bin library-loader-cli
    - name: Build GUI
      working-directory: ./ll-gui
      run: cargo build --release --bin library-loader-gui
